"""add profile_image to user table

Revision ID: 2d930527aa9f
Revises: 5a4d330ac449
Create Date: 2025-01-10 21:53:36.149323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d930527aa9f'
down_revision: Union[str, None] = '5a4d330ac449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['profile_image'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
