"""add witing field to user model

Revision ID: 3b1e6031ee4a
Revises: b0653f3317d7
Create Date: 2024-10-19 18:55:28.120859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1e6031ee4a'
down_revision: Union[str, None] = 'b0653f3317d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_waiting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_waiting')
    # ### end Alembic commands ###
