"""add email, tel, hobbies to user table

Revision ID: 5a4d330ac449
Revises: fe8daff2936d
Create Date: 2025-01-10 00:08:35.509133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4d330ac449'
down_revision: Union[str, None] = 'fe8daff2936d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tel', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hobbies', sa.ARRAY(sa.String()), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['tel'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'hobbies')
    op.drop_column('users', 'tel')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
