"""update usr model

Revision ID: 191cf599395d
Revises: 3b1e6031ee4a
Create Date: 2024-10-19 20:39:01.471483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191cf599395d'
down_revision: Union[str, None] = '3b1e6031ee4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'invite_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_waiting',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_waiting',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'invite_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
