"""Correct relationship between user and invite

Revision ID: 253a945bad57
Revises: 1ce5e0cb43cf
Create Date: 2024-10-14 18:52:48.628424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253a945bad57'
down_revision: Union[str, None] = '1ce5e0cb43cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
