"""add interests to users Table

Revision ID: f31484e38c7b
Revises: 8797723b6f17
Create Date: 2024-12-15 22:15:44.949746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31484e38c7b'
down_revision: Union[str, None] = '8797723b6f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    # ### end Alembic commands ###
