"""create Unvite Table

Revision ID: f98d3f5727a7
Revises: f6107e98a6c4
Create Date: 2024-10-13 11:31:33.037298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98d3f5727a7'
down_revision: Union[str, None] = 'f6107e98a6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    # ### end Alembic commands ###
